### ISSUE TITLE
Speed/Performance

### ISSUE THREAD

**Issue by gety9** [sixpack/sixpack#292]
Guys hi,

It's more a question than an issue. 

Does using remote A/B testing server results in loss of performance/site speed comparing to solutions where A/B testing engine is directly on web site server?
(as i understand there is a delay because sixpack server makes decisions about which alternatives to show to which users, and client must wait for a response to get alternative to render the page)

Details: We have website site on php, and at the moment all A/B points can be done in php(toggle test variation, track conversions, record KPIs) so i am wondering if in our case it's better to use php native solution placing A/B testing engine directly on web site server.

**Comment by josegonzalez** [comment]
We originally built sixpack because we deploy ~10 applications in production across various platforms, and did not want to reimplement that logic in every language - with subtly different bugs in each implementation.

Sixpack abstracts that away for you, and it was worth the request overhead for test running. If you already have something that works for your use case, great! I would stick to it.

If you want a separate service you can scale separately, or need to support multiple languages, or do not want to maintain your own service, sixpack might be for you.

Note that you will always have more overhead from making a network call vs doing something in-line, but thats because you're doing more work :)

Hope that helps.

**Comment by gety9** [comment]
@josegonzalez 

We do not have A/B testing system yet, we just evaluate different options. For situations where there is only 1 application(1 language) you would recommend to place A/B testing engine directly on same server, right?

"you will always have more overhead from making a network call vs doing something in-line"
By in-line you mean within same server, right?

**Comment by josegonzalez** [comment]
A network call will have higher overhead than something running within the same process-space, regardless of where that network call goes.

I am not making any recommendations for or against any given solution. Sixpack provides specific functionality that is enough for many use cases, and if you believe it works for your use case, great. Whether you are fine with the added overhead is not really within the realm of this repository, though I suggest you actually measure these things and make a decision.

**Comment by gety9** [comment]
@josegonzalez 

Thank you! Will test it.
